
functionality:
  name: explanatory_analysis
  info:
    label: explanatory_analysis
    summary: "Explanatory analysis of inferred GRN to provide insights about network topology and annotations"

  arguments:
    - name: --perturbation_data
      type: file
      required: false
      direction: input
      default: resources/grn-benchmark/perturbation_data.h5ad
      example: resources_test/grn-benchmark/perturbation_data.h5ad
    - name: --tf_gene_net
      type: file
      required: true
      direction: input
    - name: --peak_gene_net
      type: file
      required: false
      direction: input
    - name: --annot_peak_database
      type: file 
      required: false 
      direction: input
      must_exist: false
      example: resources/supplements/annot_peak_database.csv
    # - name: --annot_gene_database
    #   type: file 
    #   required: false 
    #   direction: input
    #   default: resources/supplements/annot_gene_database.csv
    - name: --tf_gene_indegee_fig
      type: file
      required: false
      direction: output
      default: output/tf_gene_indegree.png
    - name: --tf_gene_outdegee_fig
      type: file
      required: false
      direction: output
      default: output/tf_gene_outdegree.png
    - name: --stats
      type: file
      required: false
      direction: output
      default: output/stats.json
    
  resources:
    - type: python_script
      path: script.py
    - path: helper.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
