
functionality:
  name: peak_annotation
  namespace: exp_analysis
  info:
    label: peak_annotation
    summary: "Annotating peaks in multiomics data"

  arguments:
    - name: --multiomics_atac
      __merge__: ../../../api/file_multiomics_atac_h5ad.yaml
      direction: input
      required: true 
    - name: --annot_peak_database
      type: file
      direction: output
      required: true 
      default: resources/grn-benchmark/supp/annot_peak_database.csv
    
  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: janursa/figr:19-08-24
    # setup:
    #   - type: r
    #     bioc: []
    #     packages: []

    

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
