
__merge__: ../../../api/comp_method.yaml

functionality:
  name: grn_inference_scenicplus
  namespace: "workflows"
  info:
    label: grn_inference_scenicplus
    summary: "Infers GRNs from multiomics data using scenicplus."
  arguments:
    - name: --cistopic_object
      type: file
      direction: output

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: grn_methods/scenicplus 

platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
