__merge__: ../../../api/comp_method.yaml


functionality:
  name: GRaNIE
  namespace: "grn_methods"
  info:
    label: GRaNIE
    summary: "GRN inference using GRaNIE"
    description: |
      GRN inference using GRaNIE
    documentation_url: https://grp-zaugg.embl-community.io/GRaNIE/
  arguments:
  - name: --file_rna
    type: file
    required: true
    direction: input
    description: "Path to the RNA data file (e.g., rna.rds)."

  - name: --file_atac
    type: file
    required: true
    direction: input
    description: "Path to the ATAC data file (e.g., atac.rds)."

  - name: --temp_dir
    type: directory
    required: false
    direction: input
    default: "output/granie/"
    description: "Temporary directory for output files."

  - name: --preprocessing_clusteringMethod
    type: integer
    required: false
    default: 1
    direction: input
    description: "Seurat::FindClusters: Clustering method to use (1 = original Louvain algorithm, 2 = Louvain algorithm with multilevel refinement, 3 = SLM algorithm, 4 = Leiden algorithm)."

  - name: --preprocessing_clusterResolution
    type: float
    required: true
    direction: input
    description: "Resolution for clustering, typically between 5 and 20."

  - name: --preprocessing_SCT_nDimensions
    type: integer
    required: false
    direction: input
    default: 50
    description: "Number of dimensions for SCT, default is 50."

  - name: --genomeAssembly
    type: string
    required: true
    direction: input
    description: "Genome assembly version (e.g., hg38). Currently, hg38 and mm10 is supported."

  - name: --GRaNIE_corMethod
    type: string
    required: false
    default: "spearman"
    direction: input
    description: "Correlation method used in GRaNIE (e.g., 'spearman')."

  - name: --GRaNIE_includeSexChr
    type: boolean
    required: false
    default: true
    direction: input
    description: "Include sex chromosomes in analysis."

  - name: --GRaNIE_promoterRange
    type: integer
    required: false
    default: 250000
    direction: input
    description: "Range in base pairs for maximum distance of peak-gene connections (default is 250000)."

  - name: --GRaNIE_TF_peak.fdr.threshold
    type: float
    required: false
    default: 0.2
    direction: input
    description: "FDR threshold for TF-peak connections (default is 0.2)."

  - name: --GRaNIE_peak_gene.fdr.threshold
    type: float
    required: false
    default: 0.2
    direction: input
    description: "FDR threshold for peak-gene connections (default is 0.2)."

  - name: --GRaNIE_nCores
    type: integer
    required: true
    direction: input
    description: "Number of cores to use for computation (default is 4)."

  - name: --peak_gene
    type: file
    required: false
    direction: output
    description: "Path to the peak-gene output file (e.g., peak_gene.csv). Not yet implemented."

  - name: --prediction
    type: file
    required: true
    direction: output
    description: "Path to the prediction output file (e.g., prediction.csv)."

  - name: --useWeightingLinks
    type: boolean
    required: false
    default: false
    direction: input
    description: "Flag to indicate whether to use weighting links in analysis."

  - name: --forceRerun
    type: boolean
    required: false
    default: false
    direction: input
    description: "Flag to force rerun of the analysis regardless of existing results."

  resources:
    - type: r_script
      path: script.R


platforms:
  - type: docker
    image: chrarnold84/granieverse:latest

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
