__merge__: ../../../api/comp_method.yaml

functionality:
  name: scenic
  namespace: "grn_methods"
  info:
    label: scenic
    summary: "GRN inference using scenic"

 
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: aertslab/pyscenic:0.12.1
    setup:
    #   - type: docker
    #     run: |
    #       conda install -y -c bioconda arboreto pandas
      - type: python
        packages: [ anndata ]
  - type: native
  - type: nextflow
    directives:
      label: [onedaytime, midmem, midcpu]
