__merge__: ../../../api/comp_method.yaml

functionality:
  name: scenic
  namespace: "grn_methods"
  info:
    label: scenic
    summary: "GRN inference using scenic"

  arguments:
    - name: --rank_threshold
      type: integer
      direction: input 
      required: false
      default: 5000 
    - name: --auc_threshold
      type: double
      direction: input 
      required: false
      default: 0.05 
    - name: --nes_threshold
      type: double
      direction: input 
      required: false
      default: 3.0
      
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    # image: aertslab/pyscenic:0.12.1
    image: janursa/scenicplus:19-08-2024
    setup:
    #   - type: docker
    #     run: |
    #       conda install -y -c bioconda arboreto pandas
      - type: python
        packages: [ anndata ]
  - type: native
  - type: nextflow
    directives:
      label: [onedaytime, midmem, midcpu]
