__merge__: ../../../api/comp_method.yaml


functionality:
  name: scenicplus
  namespace: grn_methods
  info:
    label: scenicplus
    summary: "GRN inference using scenicplus"
    description: |
      GRN inference using scenicplus.
    documentation_url: https://scenicplus.readthedocs.io/en/latest/human_cerebellum.html
  arguments:
    - name: --scplus_mdata
      type: file
      required: false
      direction: output
      description: "Main output object."
      default: "scplus_mdata.h5mu"
    - name: --qc
      type: boolean
      default: false
      description: "Whether to perform quality control."
    - name: --cell_topic
      type: file 
      default: output/cell_topic.csv
      required: true
      direction: output
      description: "Cell-topics prob scores"
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: apassemi/scenicplus:1.0.0
    setup:
      - type: python
        packages: [ flatbuffers ]
  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
