__merge__: ../../../api/comp_method.yaml


functionality:
  name: scenicplus
  namespace: grn_methods
  info:
    label: scenicplus
    summary: "GRN inference using scenicplus"
    description: |
      GRN inference using scenicplus
    documentation_url: https://scenicplus.readthedocs.io/en/latest/human_cerebellum.html
  arguments:
    - name: --cistopic_object
      type: file
      direction: output
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: apassemi/scenicplus:latest
  - type: native
  - type: nextflow
    directives:
      label: [midtime,himem,hicpu]
