functionality:
  name: ppcor
  info:
    label: ppcor
    summary: "GRN inference using PPCOR"
    description: |
      GRN inference using PPCOR.
    documentation_url: https://rdrr.io/cran/ppcor/man/
  arguments:
    - name: --multiomics_rna
      type: file
      example: resources/grn-benchmark/multiomics_rna.h5ad
      info:
        label: multiomics_rna
        summary: "Multiomics RNA data"
        file_type: rds
        columns: 
          - name: dummpy
            type: string
            required: false
      required: true
      must_exist: true
    - name: --prediction
      __merge__: ../../api/file_prediction.yaml
      required: true
      direction: output
    - name: --max_n_links
      type: integer
      default: 50000
    - name: --temp_dir
      type: file
      direction: output
      default: 'output/ppcor'
    - name: --num_workers
      type: integer
      direction: input
      default: 4
  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: janursa/figr:19-08-2024
    setup:
      - type: r
        packages: [ ppcor, anndata, dplyr ]
  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
