__merge__: ../../../api/comp_method.yaml


functionality:
  name: pycistopic
  info:
    label: pycistopic
    summary: "Cis-regulatory topic modeling using pycisTopic"
    description: |
      Cis-regulatory topic modeling using pycisTopic.
    documentation_url: https://pycistopic.readthedocs.io/en/latest/
  arguments:
    - name: --qc
      type: boolean_true
      description: Whether to perform quality control
    - name: --out_dir
      type: file
      direction: output
      create_parent: true
      default: 'output/pycistopic'
    - name: --region_bin_topics_otsu
      type: file
      direction: output
      default: 'output/pycistopic/candidate_enhancers/region_bin_topics_otsu.pkl'
    - name: --region_bin_topics_top3k
      type: file
      direction: output
      default: 'output/pycistopic/candidate_enhancers/region_bin_topics_top3k.pkl'
    - name: --markers_dict
      type: file
      direction: output
      default: 'output/pycistopic/candidate_enhancers/markers_dict.pkl'
    - name: --cistopic_object
      type: file
      direction: output
      default: 'output/pycistopic/cistopic_object_with_model.pkl'

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: apassemi/scenicplus:latest
    setup:
      - type: docker
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
  - type: native
  - type: nextflow
    directives:
      label: [midtime,himem,hicpu]
