__merge__: ../../api/comp_control_method.yaml

functionality:
  name: baseline_corr
  info:
    label: baseline_corr
    summary: "Baseline based on Pearson corr"
  arguments:

    - name: --causal
      type: boolean 
      direction: input
      default: false
    - name: --seed
      type: integer
      direction: input
    - name: --multiomics_rna
      type: file
      required: true
      direction: input
      example: resources_test/grn-benchmark/multiomics_rna.h5ad
    - name: --corr_method
      type: string
      required: false
      direction: input
      default: dotproduct
      description: corr method.
    - name: --cell_type_specific
      type: boolean
      direction: input
      default: false
      description: whether to result cell type specific grn. if not, the mean of weights are taken
    - name: --metacell
      type: boolean
      direction: input
      default: false
      description: whether to pseudobulk scRNA-seq with metacells
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]
  - type: native
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
