__merge__: ../../api/comp_method.yaml

functionality:
  name: baseline_corr
  namespace: control_methods
  info:
    label: baseline_corr
    summary: "Baseline based on correlation"
  arguments:
    - name: --causal
      type: boolean 
      direction: input
      default: false
    - name: --corr_method
      type: string
      required: false
      direction: input
      default: dotproduct
      description: corr method.
    - name: --metacell
      type: boolean
      direction: input
      default: false
      description: whether to pseudobulk scRNA-seq with metacells
    - name: --impute
      type: boolean
      direction: input
      default: false
      description: whether to impute scRNA-seq

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        # packages: [ magic-impute ]
        packages: [  ]
  - type: native
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
