
__merge__: ../../../api/comp_method_r.yaml

functionality:
  name: grn_inference_granie
  namespace: "workflows"
  info:
    label: grn_inference_granie
    summary: "Infers GRNs from multiomics data using granie."
  arguments:
    - name: --subset
      type: boolean
      required: false
      default: false
      direction: input

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: grn_methods/granie 

platforms:
  - type: nextflow
    directives:
      label: [ hightime, midmem, highcpu ]
