functionality:
  name: causal_grn
  namespace: "robustness_analysis"
  info:
    label: causal_grn
    summary: Adds noise to the GRNs
  arguments:
    - name: --multiomics_rna
      type: file
      direction: input
      example: resources_test/grn-benchmark/multiomics_rna.h5ad
    
    - name: --tf_all
      type: file
      direction: input
      example: resources_test/prior/tf_all.csv

    - name: --prediction
      type: file
      direction: output 
      example: resources_test/grn_models/collectri.csv

  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: []
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]