functionality:
  name: ennet
  info:
    label: ennet
    summary: "GRN inference using ENNET"
    description: |
      GRN inference using ENNET.
    documentation_url: https://doi.org/10.1186/1752-0509-7-106
  arguments:
    - name: --multiomics_rna
      type: file
      example: resources/grn-benchmark/multiomics_rna.h5ad
      info:
        label: multiomics_rna
        summary: "Multiomics RNA data"
        file_type: rds
        columns: 
          - name: dummpy
            type: string
            required: false
      required: true
      must_exist: true
    - name: --tfs
      type: file
      example: resources/prior/tf_all.csv
      info:
        label: tfs
        summary: "List of putative TFs"
        file_type: csv
      required: true
      must_exist: true
    - name: --prediction
      __merge__: ../../../api/file_prediction.yaml
      required: true
      direction: output
    - name: --max_n_links
      type: integer
      default: 50000
    - name: --temp_dir
      type: file
      direction: output
      default: 'output/ennet'
    - name: --num_workers
      type: integer
      direction: input
      default: 4
  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: janursa/figr:19-08-2024
    setup:
      - type: r
        packages: [ foreach, plyr, anndata, dplyr ]
      - type: docker
        run: |
          wget http://github.com/slawekj/ennet/archive/master.tar.gz -O ennet.tar.gz && \
          tar -xvzf ennet.tar.gz && \
          cd ennet-master && \
          R CMD build ennet && \
          R CMD INSTALL ennet
  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
