__merge__: ../../../api/comp_method.yaml

functionality:
  name: pidc
  namespace: "grn_methods"
  info:
    label: pidc
    summary: "GRN inference using PIDC"
    description: |
      GRN inference using PIDC.
    documentation_url: https://rdrr.io/github/hmutpw/PIDC/
  
  resources:
    - type: python_script
      path: script.py
    - type: file
      path: pidc.jl

platforms:
  - type: docker
    image: apassemi/pidc:latest
  - type: native
  - type: nextflow
    directives:
      label: [threedaystime, midmem,midcpu]
