functionality:
  name: "negative_control"
  namespace: "control_methods"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--perturbation_data"
    info:
      label: "perturbation"
      summary: "Perturbation dataset for benchmarking."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "sm_name"
          type: "string"
          description: "The primary name for the (parent) compound (in a standardized\
            \ representation)\nas chosen by LINCS. This is provided to map the data\
            \ in this experiment to \nthe LINCS Connectivity Map data.\n"
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
        - name: "plate_name"
          type: "string"
          description: "Plate name 6 levels"
          required: true
        - name: "row"
          type: "string"
          description: "Row name on the plate"
          required: true
        - name: "well"
          type: "string"
          description: "Well name on the plate"
          required: true
        - name: "cell_count"
          type: "string"
          description: "Number of single cells pseudobulked"
          required: true
        layers:
        - name: "n_counts"
          type: "double"
          description: "Pseudobulked values using mean approach"
          required: true
        - name: "pearson"
          type: "double"
          description: "Normalized values using pearson residuals"
          required: false
        - name: "lognorm"
          type: "double"
          description: "Normalized values using shifted logarithm "
          required: false
    example:
    - "resources_test/grn-benchmark/perturbation_data.h5ad"
    default:
    - "resources/grn-benchmark/perturbation_data.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_rna"
    info:
      label: "multiomics rna"
      summary: "RNA expression for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources_test/grn-benchmark/multiomics_rna.h5ad"
    default:
    - "resources/grn-benchmark/multiomics_rna.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--layer"
    description: "Which layer of pertubation data to use to find tf-gene relationships."
    info: null
    default:
    - "scgen_pearson"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--prediction"
    info:
      label: "GRN"
      summary: "GRN prediction"
      file_type: "csv"
      columns:
      - name: "source"
        description: "Source of regulation"
        type: "string"
        required: true
      - name: "target"
        description: "Target of regulation"
        type: "string"
        required: true
      - name: "weight"
        description: "Weight of regulation"
        type: "float"
        required: true
    example:
    - "resources_test/grn_models/collectri.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--tf_all"
    info: null
    example:
    - "resources_test/prior/tf_all.csv"
    default:
    - "resources/prior/tf_all.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources_test/grn-benchmark"
    dest: "resources_test/grn-benchmark"
  - type: "file"
    path: "resources_test/prior"
    dest: "resources_test/prior"
  info:
    label: "Negative control"
    summary: "Source-target links based on random assignment"
    description: "Randomly assigns regulatory links to tf-target links with a given\
      \ tf and target list. This is to perform near random.\n"
    type: "control_method"
    type_info:
      label: "Control Method"
      summary: "A control method."
      description: "A control method to serve as a quality control for the GRN inference\
        \ benchmark.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  target_organization: "openproblems-bio/task_grn_inference"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_grn_inference"
  setup:
  - type: "python"
    user: false
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/control_methods/negative_control/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/control_methods/negative_control"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/control_methods/negative_control/negative_control"
  viash_version: "0.8.6"
  git_commit: "e1e727ab273fcceddd2a0b2d31b520e76d3a0cc3"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
