
functionality:
  name: subset_hvg
  namespace: "multiomics"
  info:
    label: subset_hvg
    summary: "Receives multiomics data and subsets it for hvg"
  arguments:
    - name: --multiomics_rna
      type: file 
      required: true
      direction: input
      example: resources/grn-benchmark/multiomics_rna.h5ad
    - name: --multiomics_atac
      type: file 
      required: true
      direction: input
      example: resources/grn-benchmark/multiomics_atac.h5ad

    - name: --multiomics_rna_d0_hvg
      type: file 
      required: false
      direction: output
      example: resources/grn-benchmark/multiomics_rna_d0_hvg.h5ad
    - name: --multiomics_atac_d0
      type: file 
      required: false
      direction: output
      example: resources/grn-benchmark/multiomics_atac_d0.h5ad

  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ scikit-misc ]
    

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
