functionality:
  name: "run_grn_evaluation"
  namespace: "workflows"
  version: "build-main"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--perturbation_data"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--layer"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--prediction"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--subsample"
      info: null
      default:
      - 2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--reg_type"
      info: null
      default:
      - "ridge"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--method_id"
      info: null
      example:
      - "collectri"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--max_workers"
      info: null
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--tf_all"
      info: null
      default:
      - "resources/prior/tf_all.csv"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--scores"
      info: null
      default:
      - "scores.yaml"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--metric_configs"
      info: null
      default:
      - "metric_configs.yaml"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "../../api/task_info.yaml"
  info:
    label: "run_grn_evaluation"
    summary: "Evaluates GRNs and provides scores using regression analysis."
  status: "enabled"
  dependencies:
  - name: "common/extract_metadata"
    repository:
      type: "github"
      name: ""
      repo: "openproblems-bio/openproblems-v2"
      tag: "main_build"
      localPath: "/tmp/viash_hub_repo5994068711330865865"
    foundConfigPath: "/tmp/viash_hub_repo5994068711330865865/target/nextflow/common/extract_metadata/.config.vsh.yaml"
    configInfo:
      functionalityName: "extract_metadata"
      git_remote: "https://github.com/openproblems-bio/openproblems-v2"
      viash_version: "0.8.0"
      config: "/home/runner/work/openproblems-v2/openproblems-v2/src/common/extract_metadata/config.vsh.yaml"
      functionalityNamespace: "common"
      output: "/home/runner/work/openproblems-v2/openproblems-v2/target/nextflow/common/extract_metadata"
      platform: "nextflow"
      git_commit: "d0bc03fb05d43fb26f51c6fe6aa2e2a2f7ff5ade"
      executable: "/home/runner/work/openproblems-v2/openproblems-v2/target/nextflow/common/extract_metadata/extract_metadata"
    writtenPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/dependencies/github/openproblems-bio/openproblems-v2/main_build/nextflow/common/extract_metadata"
  - name: "metrics/regression_2"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/metrics/regression_2/config.vsh.yaml"
    configInfo:
      functionalityName: "regression_2"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_benchmark"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/metrics/regression_2/config.vsh.yaml"
      functionalityNamespace: "metrics"
      output: ""
      platform: ""
      git_commit: "946543ddef68017ad16e8f204b21540d3a06f6fa"
      executable: "/nextflow/metrics/regression_2/main.nf"
    writtenPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/nextflow/metrics/regression_2"
  - name: "metrics/regression_1"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/metrics/regression_1/config.vsh.yaml"
    configInfo:
      functionalityName: "regression_1"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_benchmark"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/metrics/regression_1/config.vsh.yaml"
      functionalityNamespace: "metrics"
      output: ""
      platform: ""
      git_commit: "946543ddef68017ad16e8f204b21540d3a06f6fa"
      executable: "/nextflow/metrics/regression_1/main.nf"
    writtenPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/nextflow/metrics/regression_1"
  - name: "control_methods/positive_control"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/control_methods/positive_control/config.vsh.yaml"
    configInfo:
      functionalityName: "positive_control"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_benchmark"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/control_methods/positive_control/config.vsh.yaml"
      functionalityNamespace: "control_methods"
      output: ""
      platform: ""
      git_commit: "946543ddef68017ad16e8f204b21540d3a06f6fa"
      executable: "/nextflow/control_methods/positive_control/main.nf"
    writtenPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/nextflow/control_methods/positive_control"
  - name: "control_methods/negative_control"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/control_methods/negative_control/config.vsh.yaml"
    configInfo:
      functionalityName: "negative_control"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_benchmark"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/control_methods/negative_control/config.vsh.yaml"
      functionalityNamespace: "control_methods"
      output: ""
      platform: ""
      git_commit: "946543ddef68017ad16e8f204b21540d3a06f6fa"
      executable: "/nextflow/control_methods/negative_control/main.nf"
    writtenPath: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/nextflow/control_methods/negative_control"
  repositories:
  - type: "github"
    name: "openproblemsv2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
    localPath: ""
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/src/workflows/run_grn_evaluation/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/nextflow/workflows/run_grn_evaluation"
  executable: "/home/runner/work/task_grn_benchmark/task_grn_benchmark/target/nextflow/workflows/run_grn_evaluation/main.nf"
  viash_version: "0.8.6"
  git_commit: "946543ddef68017ad16e8f204b21540d3a06f6fa"
  git_remote: "https://github.com/openproblems-bio/task_grn_benchmark"
