__merge__: ../../api/comp_control_method.yaml
functionality:
  name: positive_control
  info:
    label: Positive control
    summary: Source-target links based on perturbation data
    description: |
      By directly training on perturbation data, positive control is expected to learn more accurate tf-gene connections.

  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]