
functionality:
  name: run_robustness_analysis
  namespace: "workflows"
  info:
    label: run_robustness_analysis
    summary: "Evaluates GRNs and provides scores using regression analysis."

    
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: ../../api/task_info.yaml
  dependencies:
    - name: common/extract_metadata
      repository: openproblemsv2
    - name: metrics/regression_1
  repositories:
    - name: openproblemsv2
      type: github
      repo: openproblems-bio/openproblems-v2
      tag: main_build
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
