__merge__: ../../api/comp_metric.yaml
functionality:
  name: regression_1
  namespace: "metrics"
  info:
    label: Regression 1
    summary: Calculates R2 score for regression 1
    description: |
      Calculates R2 score using regression approach 1.
  arguments:
    - name: --layer
      type: string
      direction: input
      required: false
      default: pearson
    - name: --min_tf
      type: integer
      direction: input
      description: calculate the scores for the given min tfs in addition to the default 
      required: false
  resources:
    - type: python_script
      path: script.py
    - path: main.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ lightgbm==4.3.0, numpy==1.26.4 ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]