__merge__: ../../../api/comp_method.yaml


functionality:
  name: figr
  namespace: "grn_methods"
  info:
    label: figr
    summary: "GRN inference using figr"
    description: |
      GRN inference using figr.
    documentation_url: https://buenrostrolab.github.io/FigR/articles/FigR_shareseq.html
  arguments:
    - name: --multiomics_rna
      type: file
      required: true
      direction: input
    - name: --multiomics_atac
      type: file
      required: true
      direction: input
    - name: --prediction
      __merge__: ../../api/file_prediction.yaml
      required: true
      direction: output
    
    - name: --cell_topic
      type: file
      example: resources/grn-benchmark/supp/cell_topic.csv
      info:
        label: Cell topic probability database
        summary: "annotation file"
        file_type: csv
        columns: 
          - name: topic
            type: string
            required: false
      required: true

    - name: --temp_dir
      type: string
      direction: input
      default: 'output/figr'
    - name: --num_workers
      type: integer
      direction: input
      default: 4
    - name: --n_topics
      type: integer 
      direction: input
      default: 48
  resources:
    - type: r_script
      path: script.R


platforms:
  - type: docker
    image: janursa/figr:19-08-2024

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
